### ISSUE TITLE
did not work with arduino 1.5.5

### ISSUE THREAD

**Issue by doors666** [pauldreik/arduino-due-makefile#4]
dir structure has changed, I needed to add hardware/ to a lot of dirs. e.g.

CXX:=$(ADIR)/hardware/tools/g++_arm_none_eabi/bin/arm-none-eabi-g++
CC:=$(ADIR)/hardware/tools/g++_arm_none_eabi/bin/arm-none-eabi-gcc
C:=$(CC)
SAM:=hardware/arduino/sam/
CMSIS:=hardware/arduino/sam/system/CMSIS/
LIBSAM:=hardware/arduino/sam/system/libsam
TMPDIR:=$(PWD)/build
AR:=$(ADIR)/hardware/tools/g++_arm_none_eabi/bin/arm-none-eabi-ar

**Comment by pauldreik** [comment]
Sometimes it takes a few years :-(
But now it works with 1.6.11
